#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
core/consolidation.py — THE SYSTEM READS ITS OWN MEMORY (3 Sep 2026).

WHAT THIS REPLACES. experiments/dreams/dream.py was rung 2 of the local-brain
ladder: after each cycle, ask a 3b model to write a five-line autobiographical note.
It has never run. There are zero .md notes on disk, no scheduled task, and no caller
in any .py, .ps1 or .bat in this repo. It was also the wrong shape for the job — a
narrative generated by a model is not a reading of the record, it is a paraphrase of
one, and check.py existed precisely because nobody could tell those apart.

Consolidation does the thing the daily cycle structurally cannot. Each night the
cycle sees ONE reading per metric and asks whether it moved. It cannot see a series.
Over 30 days a metric can drift monotonically while every single night's delta sits
inside the noise, and no nightly step will ever raise it. This module reads the
archive as a TIME SERIES and asks a different question: what has been moving all
along that no single night could show?

NO MODEL. Not Ollama, not a subprocess, not an HTTP call. Every number here comes
from least squares over values the cycle already sealed into
cortex_memory/archive/cycle_NNNNNN/signals.json. That is deliberate and it is the
main design decision: the output is a falsifiable prediction with an interval, and a
prediction is worth exactly as much as the procedure that produced it is inspectable.
A 3b model's guess at a trend cannot be audited, cannot be reproduced, and cannot be
scored against a method — which is what core/belief_revision.py needs to do with it.

WHAT IT EMITS. Dated, falsifiable hypotheses to memory/consolidation_queue.json:

    axis, metric, direction (up|down|flat), horizon_days (7|30|90),
    predicted, lo, hi, made_on, due_on, n_points, span_days, slope_per_day, r2

A hypothesis is only emitted when the drift is BOTH real enough to state (the fitted
move over the horizon clears one residual sigma) and small enough per night to have
been invisible (which is the whole reason this runs here and not in the cycle). The
interval is the falsifier: if the observed value on due_on lands outside [lo, hi],
the hypothesis was wrong, and it says so without anyone having to interpret it.

PROOF IT RAN: memory/consolidation_latest.json — cycles_read, series_considered,
emitted, and why each rejection happened. A quiet night writes it too, with
emitted=0, because a module that only leaves a trace when it has something to say
cannot be told from one that has stopped running.

THE READER. memory/consolidation_queue.json is consumed by the nightly hypothesis
generator (fast_cycle_runner step 20.06, core/hypothesis_intake.py), which
pre-registers these into cortex_memory/hypotheses/pending.json where the evaluator
(step 20.05) can grade them. WIRE_FIRST: this producer shipped with its reader.

  venv\\Scripts\\python.exe -m core.consolidation --selftest
  venv\\Scripts\\python.exe -m core.consolidation --dry-run
"""
from __future__ import annotations

import json
import math
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ARCHIVE = REPO / "cortex_memory" / "archive"
QUEUE = REPO / "memory" / "consolidation_queue.json"
LATEST = REPO / "memory" / "consolidation_latest.json"

WINDOW_DAYS = 30          # how far back to read
MIN_POINTS = 5            # fewer than this is not a series, it is anecdote
MIN_SPAN_DAYS = 10        # a slope fitted over three days is not slow drift
HORIZONS = (7, 30, 90)
MAX_PER_RUN = 40          # a queue nobody can read is the same as no queue


# ── reading the archive ───────────────────────────────────────────────────────

def _rel(p: Path) -> str:
    """Repo-relative POSIX for the record, absolute when the path is off-tree.
    A test points the queue at a tmp dir, and relative_to() raises there."""
    try:
        return str(p.relative_to(REPO)).replace("\\", "/")
    except ValueError:
        return str(p).replace("\\", "/")


def read_cycles(window_days: int = WINDOW_DAYS, archive: Path | None = None,
                today: date | None = None) -> list:
    """Every sealed cycle in the window, oldest first. Never raises on one bad dir."""
    root = archive or ARCHIVE
    today = today or datetime.now(timezone.utc).date()
    cutoff = today - timedelta(days=window_days)
    out = []
    if not root.is_dir():
        return out
    for d in sorted(root.glob("cycle_*")):
        f = d / "signals.json"
        if not f.is_file():
            continue
        try:
            s = json.loads(f.read_text(encoding="utf-8"))
            when = datetime.fromisoformat(
                str(s.get("timestamp")).replace("Z", "+00:00")).date()
        except Exception:
            continue
        if when < cutoff or when > today:
            continue
        out.append({"dir": d.name, "date": when,
                    "signals": s.get("signals") or []})
    out.sort(key=lambda r: r["date"])
    return out


def build_series(cycles: list) -> dict:
    """(axis, metric) -> [(date, value)], deduplicated to one point per day.

    Several cycles can land on one date (a catch-up run, a manual cycle). Two
    readings of the same day are not two observations of a trend, so the last one
    wins — otherwise a day with three cycles silently gets triple the leverage in
    the fit.
    """
    by_day: dict = {}
    for c in cycles:
        for sig in c["signals"]:
            if not isinstance(sig, dict):
                continue
            axis, metric = sig.get("domain"), sig.get("metric")
            val = sig.get("value")
            if not axis or not metric or not isinstance(val, (int, float)):
                continue
            by_day[(axis, metric, c["date"])] = float(val)
    series: dict = {}
    for (axis, metric, when), val in by_day.items():
        series.setdefault((axis, metric), []).append((when, val))
    for k in series:
        series[k].sort(key=lambda p: p[0])
    return series


# ── the arithmetic (least squares, no library, no model) ──────────────────────

def _fit(points: list) -> dict | None:
    """Least-squares line over day-offsets. Returns slope/intercept/residual sigma."""
    n = len(points)
    if n < 2:
        return None
    t0 = points[0][0]
    xs = [(p[0] - t0).days for p in points]
    ys = [p[1] for p in points]
    mx, my = sum(xs) / n, sum(ys) / n
    sxx = sum((x - mx) ** 2 for x in xs)
    if sxx == 0:
        return None
    slope = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / sxx
    intercept = my - slope * mx
    resid = [y - (intercept + slope * x) for x, y in zip(xs, ys)]
    sse = sum(r * r for r in resid)
    sst = sum((y - my) ** 2 for y in ys)
    sigma = math.sqrt(sse / (n - 2)) if n > 2 else 0.0
    # night-to-night movement: what a single cycle COULD have seen
    steps = [abs(ys[i] - ys[i - 1]) for i in range(1, n)]
    return {"slope": slope, "intercept": intercept, "sigma": sigma,
            "r2": (1 - sse / sst) if sst > 0 else 0.0,
            "n": n, "span_days": xs[-1], "last_x": xs[-1], "last_y": ys[-1],
            "mean_abs_step": (sum(steps) / len(steps)) if steps else 0.0,
            "t0": t0}


def _hypothesis(axis: str, metric: str, fit: dict, made_on: date) -> dict | None:
    """Turn a fit into ONE falsifiable claim, or None if it says nothing.

    The two gates, and why each exists:
      REAL ENOUGH — the fitted move over the horizon must clear one residual sigma.
        Below that the line is inside its own noise and the "prediction" would be
        unfalsifiable in practice: almost any outcome would land in the interval.
      SLOW ENOUGH — the move per night must be under half the mean night-to-night
        step. If it were bigger, a nightly step could have caught it, and this
        module would be duplicating work the cycle already does rather than seeing
        what the cycle structurally cannot.
    """
    sigma = fit["sigma"]
    if sigma <= 0:
        return None
    per_day = abs(fit["slope"])
    if per_day >= 0.5 * fit["mean_abs_step"] and fit["mean_abs_step"] > 0:
        return None                      # fast enough for a nightly step to see
    for h in HORIZONS:
        move = abs(fit["slope"]) * h
        if move < sigma:
            continue                     # inside the noise at this horizon
        pred = fit["intercept"] + fit["slope"] * (fit["last_x"] + h)
        # prediction interval: residual spread widened for a mean estimated from n
        half = 2.0 * sigma * math.sqrt(1.0 + 1.0 / fit["n"])
        return {
            "axis": axis,
            "metric": metric,
            "direction": "up" if fit["slope"] > 0 else "down",
            "horizon_days": h,
            "made_on": made_on.isoformat(),
            "due_on": (made_on + timedelta(days=h)).isoformat(),
            "last_value": round(fit["last_y"], 6),
            "predicted": round(pred, 6),
            "lo": round(pred - half, 6),
            "hi": round(pred + half, 6),
            "slope_per_day": round(fit["slope"], 8),
            "residual_sigma": round(sigma, 6),
            "r2": round(fit["r2"], 4),
            "n_points": fit["n"],
            "span_days": fit["span_days"],
            "mean_abs_step": round(fit["mean_abs_step"], 6),
            "method": "linear_drift",
            "source": "core/consolidation.py",
            "falsifier": ("the observed value on due_on falls outside [lo, hi]"),
        }
    return None


# ── the run ───────────────────────────────────────────────────────────────────

def run(write: bool = True, window_days: int = WINDOW_DAYS,
        archive: Path | None = None, today: date | None = None,
        queue: Path | None = None, latest: Path | None = None) -> dict:
    today = today or datetime.now(timezone.utc).date()
    cycles = read_cycles(window_days, archive, today)
    series = build_series(cycles)

    # The rejection taxonomy is the useful half of the output on a night with
    # nothing to say. On 3 Sep 2026, 46 of 48 series were PERFECTLY CONSTANT across
    # the whole 30-day window — the World Bank annual indicators do not move
    # nightly, so there is no drift to find and no amount of tuning would invent
    # one. "constant_series" says that; "says_nothing" would have hidden it.
    emitted, rejected = [], {"too_few_points": 0, "too_short_a_span": 0,
                             "degenerate": 0, "constant_series": 0,
                             "fast_enough_for_a_nightly_step": 0,
                             "inside_the_noise_at_every_horizon": 0}
    for (axis, metric), pts in sorted(series.items()):
        if len(pts) < MIN_POINTS:
            rejected["too_few_points"] += 1
            continue
        fit = _fit(pts)
        if fit is None:
            rejected["degenerate"] += 1
            continue
        if fit["span_days"] < MIN_SPAN_DAYS:
            rejected["too_short_a_span"] += 1
            continue
        if fit["sigma"] <= 0:
            rejected["constant_series"] += 1
            continue
        if fit["mean_abs_step"] > 0 and \
                abs(fit["slope"]) >= 0.5 * fit["mean_abs_step"]:
            rejected["fast_enough_for_a_nightly_step"] += 1
            continue
        h = _hypothesis(axis, metric, fit, today)
        if h is None:
            rejected["inside_the_noise_at_every_horizon"] += 1
            continue
        emitted.append(h)

    # strongest first, so a truncated queue keeps the best evidence
    emitted.sort(key=lambda h: (-h["r2"], h["axis"], h["metric"]))
    truncated = max(0, len(emitted) - MAX_PER_RUN)
    emitted = emitted[:MAX_PER_RUN]

    rec = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "made_on": today.isoformat(),
        "window_days": window_days,
        "cycles_read": len(cycles),
        "date_range": ([cycles[0]["date"].isoformat(),
                        cycles[-1]["date"].isoformat()] if cycles else None),
        "series_considered": len(series),
        "emitted": len(emitted),
        "truncated": truncated,
        "rejected": rejected,
        "axes": sorted({h["axis"] for h in emitted}),
        "uses_model": False,
        "queue": _rel(queue or QUEUE),
    }

    if write:
        q = queue or QUEUE
        q.parent.mkdir(parents=True, exist_ok=True)
        q.write_text(json.dumps({"made_on": today.isoformat(),
                                 "hypotheses": emitted}, ensure_ascii=False,
                                indent=2), encoding="utf-8")
        (latest or LATEST).write_text(json.dumps(rec, ensure_ascii=False, indent=2),
                                      encoding="utf-8")
    rec["hypotheses"] = emitted
    return rec


def summary_line(rec: dict) -> str:
    if not rec["cycles_read"]:
        return ("[CONSOLIDATION] 0 cycles in the window — nothing to consolidate "
                "(is cortex_memory/archive/ being written?)")
    if not rec["emitted"]:
        return (f"[CONSOLIDATION] {rec['cycles_read']} cycles, "
                f"{rec['series_considered']} series -> 0 hypotheses "
                f"(nothing is drifting slowly enough to be worth a claim)")
    return (f"[CONSOLIDATION] {rec['cycles_read']} cycles read "
            f"({rec['date_range'][0]}..{rec['date_range'][1]}), "
            f"{rec['series_considered']} series -> {rec['emitted']} hypotheses "
            f"across {len(rec['axes'])} axes")


FORBIDDEN = frozenset({"subprocess", "requests", "urllib", "http", "socket",
                       "ollama", "openai", "httpx", "aiohttp"})


def module_imports(path: Path | None = None) -> set:
    """Every module this file imports, read off the AST."""
    import ast
    tree = ast.parse((path or Path(__file__)).read_text(encoding="utf-8"))
    found = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            found.update(a.name.split(".")[0] for a in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            found.add(node.module.split(".")[0])
    return found


def imported_forbidden(path: Path | None = None) -> set:
    """The promise in the docstring, made checkable: no model, no network, no shell."""
    return module_imports(path) & FORBIDDEN


def _selftest() -> int:
    print("core/consolidation --selftest")
    print(f"  archive              : {'LIVE ' if ARCHIVE.is_dir() else 'INERT '}{ARCHIVE}")
    # Checked against the AST, not the text: this file's own docstring says the
    # words "Ollama" and "subprocess" while promising not to use them, and a
    # substring check cannot tell a promise from a call.
    print(f"  no model / no network: {'OK' if not imported_forbidden() else 'VIOLATION'}"
          f" (imports: {', '.join(sorted(module_imports())) or 'stdlib only'})")
    for rel, needle in (("core/hypothesis_intake.py", "consolidation_queue"),
                        ("fast_cycle_runner.py", "consolidation")):
        p = REPO / rel
        wired = p.is_file() and needle in p.read_text(encoding="utf-8", errors="ignore")
        print(f"  reader {rel:28s}: {'LIVE' if wired else 'INERT'}")
    rec = run(write=False)
    print("  dry run -> " + summary_line(rec).replace("[CONSOLIDATION] ", ""))
    for h in rec["hypotheses"][:3]:
        print(f"      {h['axis']}/{h['metric']}: {h['direction']} to "
              f"{h['predicted']} [{h['lo']}, {h['hi']}] by {h['due_on']} "
              f"(r2={h['r2']}, n={h['n_points']})")
    return 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(_selftest())
    rec = run(write="--dry-run" not in sys.argv)
    print(summary_line(rec))
    if "--json" in sys.argv:
        print(json.dumps(rec, ensure_ascii=False, indent=2))
