"""
core/creative_tick.py - the background creative thinking phase.

WHAT THIS IS
    A daily, quiet-hour tick that produces HYPOTHESES about the system's own
    observations. Not summaries. Not scores. Falsifiable statements with a
    horizon date, which will later be judged right or wrong by the world.

WHY IT EXISTS
    Every other loop in CORTEX answers a question that was already asked
    (what is the CO2 value, did the cycle run, is this quote grounded).
    Nothing in the system asks a question nobody posed. This does.

WHY IT IS DETERMINISTIC FIRST
    Seeds are generated by CODE from real data - rule violations and monotone
    trends. The LLM only ARTICULATES a seed that already exists; it never
    invents one. An LLM asked to "be creative" about a civilization dataset
    produces plausible sentences with no referent. A seed produced by a rule
    violation has a referent by construction.

STATUS BEFORE THIS FILE
    memory/idea_stream.jsonl did not exist. The creative phase was specified
    (SPEC_penumbra_pulse.md Part B item 7) and never built. Zero ideas produced.

WHAT IS INERT IN THIS REPO RIGHT NOW - verified 2026-08-03, not assumed
    core/metta_oracle.py DOES NOT EXIST. Therefore:
      - seed generator 1 (rule violations) yields NOTHING and will keep
        yielding nothing until that module exists;
      - the mentor pass returns mentor="unavailable" and every idea is
        surfaced unchecked;
      - the penumbra model_anomaly door is unreachable.
    Only seed generator 2 (monotone trends) is live. Run --selftest before
    trusting any claim about what this module is doing.

WALL COMPLIANCE (BOUNDARIES.md S I / S V)
    This module writes exactly one file: memory/idea_stream.jsonl (append only).
    It actuates nothing. It changes no score, no source, no config. It cannot
    promote its own ideas; surfacing is done by the needs report, and the human
    retains the S V right to read the whole stream including what was rejected.

METRIC DISCIPLINE
    NEVER track accept-rate as a quality measure. An idea generator optimised
    for approval learns to please, not to predict. The only metric is:
    of the ideas whose test_horizon has passed, what fraction resolved TRUE.
    Ideas start with outcome=null and stay that way until their horizon date.

USAGE
    python core/creative_tick.py --dry-run      # print, write nothing
    python core/creative_tick.py                # run and append
    python core/creative_tick.py --status       # stream stats, no generation
    python core/creative_tick.py --due          # ideas whose horizon has passed
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MEMORY = REPO / "memory"
IDEA_STREAM = MEMORY / "idea_stream.jsonl"

QUIET_HOUR = 21          # first tick after this local hour
IDLE_HOURS = 6           # or if nothing fired for this long
TREND_MIN_POINTS = 5     # a trend seed needs this many monotone points
MAX_IDEAS_PER_TICK = 6   # a portion, not a flood

# ---------------------------------------------------------------------------
# optional repo integrations - the tick degrades, it does not crash
# ---------------------------------------------------------------------------

def _try(fn, default=None):
    try:
        return fn()
    except Exception:
        return default


def _load_metta_oracle():
    try:
        from core.metta_oracle import ask  # type: ignore
        return ask
    except Exception:
        return None


def _load_llm():
    try:
        from core.groq_backend import call_groq  # type: ignore
        return call_groq
    except Exception:
        return None


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _now():
    return datetime.now(timezone.utc)


def _iso(dt):
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _read_jsonl(path, limit=None):
    if not path.exists():
        return []
    out = []
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    if limit:
        return out[-limit:]
    return out


def _is_ascii(text):
    try:
        text.encode("ascii")
        return True
    except (UnicodeEncodeError, AttributeError):
        return False


# ---------------------------------------------------------------------------
# SEED GENERATOR 1 - rule violations (deterministic)
# ---------------------------------------------------------------------------

def seeds_from_rule_violations(levels):
    """Any fired rule violation from the symbolic oracle becomes a seed.

    The proof trace travels WITH the seed. An idea that cannot show why it
    was born is not admissible.
    """
    ask = _load_metta_oracle()
    if ask is None:
        return []
    result = _try(lambda: ask(levels), default=None)
    if not result:
        return []
    seeds = []
    violations = result.get("violations") if isinstance(result, dict) else None
    for v in (violations or []):
        seeds.append({
            "kind": "hypothesis",
            "seed": "rule_violation",
            "rule": v.get("rule"),
            "proof": v.get("proof") or v.get("trace"),
            "subject": v.get("subject") or v.get("axis"),
            "raw": v,
        })
    return seeds


# ---------------------------------------------------------------------------
# SEED GENERATOR 2 - monotone trends (deterministic)
# ---------------------------------------------------------------------------

def _monotone_run(series):
    """Return (direction, length) of the monotone run ending at the last point."""
    if len(series) < 2:
        return (0, 0)
    direction = 0
    length = 1
    for i in range(len(series) - 1, 0, -1):
        d = 0
        if series[i] > series[i - 1]:
            d = 1
        elif series[i] < series[i - 1]:
            d = -1
        else:
            break
        if direction == 0:
            direction = d
        if d != direction:
            break
        length += 1
    return (direction, length)


def seeds_from_trends(axis_series):
    """axis_series: {axis_name: [floats, oldest -> newest]}"""
    seeds = []
    for axis, series in (axis_series or {}).items():
        clean = [x for x in series if isinstance(x, (int, float))]
        direction, length = _monotone_run(clean)
        if direction == 0 or length < TREND_MIN_POINTS:
            continue
        seeds.append({
            "kind": "hypothesis",
            "seed": "trend",
            "subject": axis,
            "direction": "rising" if direction > 0 else "falling",
            "run_length": length,
            "series_tail": clean[-TREND_MIN_POINTS:],
        })
    return seeds


# ---------------------------------------------------------------------------
# ARTICULATION - the only place a model speaks
# ---------------------------------------------------------------------------

ARTICULATE_PROMPT = """You are given a SEED: a fact already established by deterministic code from real data.
Turn it into ONE falsifiable hypothesis.

Rules, all mandatory:
- Do not introduce any fact not present in the seed.
- The hypothesis must be falsifiable by a future observation.
- Give an explicit horizon: a number of days after which it can be judged.
- State plainly what observation would make it FALSE.
- Answer in English only.

Return strict JSON with exactly these keys:
{"idea": str, "dimension": str, "falsifiable_test": str, "horizon_days": int, "would_be_false_if": str}

SEED:
"""


def articulate(seed):
    call = _load_llm()
    if call is None:
        return _articulate_fallback(seed)
    raw = _try(lambda: call(ARTICULATE_PROMPT + json.dumps(seed, ensure_ascii=False)), default=None)
    if not raw:
        return _articulate_fallback(seed)
    text = raw if isinstance(raw, str) else str(raw)
    start, end = text.find("{"), text.rfind("}")
    if start < 0 or end <= start:
        return _articulate_fallback(seed)
    obj = _try(lambda: json.loads(text[start:end + 1]), default=None)
    return obj or _articulate_fallback(seed)


def _articulate_fallback(seed):
    """No model available - still produce a real, testable statement.

    A degraded creative tick that produces a plain trend hypothesis is far
    better than one that produces nothing. Deterministic first means the
    system can think without a model at all.
    """
    if seed.get("seed") == "trend":
        d = seed["direction"]
        return {
            "idea": "Axis %s has moved %s for %d consecutive observations; it will continue in the same direction at the next observation." % (seed["subject"], d, seed["run_length"]),
            "dimension": seed["subject"],
            "falsifiable_test": "at the next scored observation of %s, the value moves in the same direction" % seed["subject"],
            "horizon_days": 30,
            "would_be_false_if": "the next observation reverses or is flat",
            "articulated_by": "deterministic_fallback",
        }
    if seed.get("seed") == "rule_violation":
        return {
            "idea": "Rule %s is violated for %s; the violation persists at the next cycle." % (seed.get("rule"), seed.get("subject")),
            "dimension": seed.get("subject") or "unknown",
            "falsifiable_test": "the same rule check at the next cycle",
            "horizon_days": 7,
            "would_be_false_if": "the rule check passes at the next cycle",
            "articulated_by": "deterministic_fallback",
        }
    return None


# ---------------------------------------------------------------------------
# GUARDS
# ---------------------------------------------------------------------------

def guard(idea, seed, grounded_on):
    """Return (ok, reason). Every rejection reason is typed and recorded."""
    if not idea:
        return (False, "articulation_failed")
    if not idea.get("idea"):
        return (False, "empty_idea")
    if not idea.get("falsifiable_test"):
        return (False, "no_falsifiable_test")
    horizon = idea.get("horizon_days")
    if not isinstance(horizon, int) or horizon <= 0:
        return (False, "no_horizon")
    if not idea.get("would_be_false_if"):
        return (False, "no_falsifier")
    if not grounded_on:
        return (False, "ungrounded")
    for ref in grounded_on:
        p = REPO / ref
        if not p.exists():
            return (False, "ungrounded_ref_missing:%s" % ref)
    # language guard - a rationale a maintainer cannot read is not auditable
    blob = " ".join(str(idea.get(k, "")) for k in ("idea", "falsifiable_test", "would_be_false_if"))
    if not _is_ascii(blob):
        return (False, "non_english_output")
    return (True, "")


def mentor_pass(idea, seed):
    """Consistency check against the symbolic rules.

    A contradiction does NOT delete the idea. It is kept in the stream as
    training material and NOT surfaced - except when the idea contradicts a
    known rule while citing a well-sourced observation, in which case it is a
    model_anomaly and goes to the penumbra. That is the novelty door: the
    system is allowed to be right against its own rules, but only in the open,
    and only with a citation.
    """
    ask = _load_metta_oracle()
    if ask is None:
        return {"mentor": "unavailable", "surface": True}
    verdict = _try(lambda: ask({"check_consistency": idea.get("idea")}), default=None)
    if not verdict:
        return {"mentor": "unavailable", "surface": True}
    if verdict.get("contradiction"):
        well_sourced = bool(seed.get("proof")) or bool(seed.get("series_tail"))
        return {
            "mentor": "mentor_rejected",
            "proof": verdict.get("proof"),
            "surface": False,
            "penumbra": "model_anomaly" if well_sourced else None,
        }
    return {"mentor": "consistent", "surface": True}


# ---------------------------------------------------------------------------
# TICK
# ---------------------------------------------------------------------------

def should_tick(last_tick_iso, last_threshold_fire_iso, now=None):
    now = now or _now()
    if last_tick_iso:
        last = _try(lambda: datetime.strptime(last_tick_iso, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc))
        if last and (now - last) < timedelta(hours=20):
            return (False, "already_ticked_today")
    if now.hour >= QUIET_HOUR:
        return (True, "quiet_hour")
    if last_threshold_fire_iso:
        fired = _try(lambda: datetime.strptime(last_threshold_fire_iso, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc))
        if fired and (now - fired) > timedelta(hours=IDLE_HOURS):
            return (True, "idle_%dh" % IDLE_HOURS)
    return (False, "not_due")


def run_tick(levels, axis_series, grounded_on, dry_run=False):
    now = _now()
    seeds = seeds_from_rule_violations(levels) + seeds_from_trends(axis_series)
    existing = _read_jsonl(IDEA_STREAM)
    seen = {e.get("seed_key") for e in existing}

    records = []
    for seed in seeds:
        seed_key = "%s:%s:%s" % (seed.get("seed"), seed.get("subject"), seed.get("rule") or seed.get("direction"))
        if seed_key in seen:
            continue
        idea = articulate(seed)
        ok, reason = guard(idea, seed, grounded_on)
        base = {
            "ts": _iso(now),
            "seed_key": seed_key,
            "seed": seed,
            "kind": seed.get("kind", "hypothesis"),
            "grounded_on": grounded_on,
        }
        if not ok:
            records.append(dict(base, status="rejected", reject_reason=reason, idea=idea))
            continue
        m = mentor_pass(idea, seed)
        horizon_date = _iso(now + timedelta(days=int(idea["horizon_days"])))
        records.append(dict(
            base,
            status="accepted" if m.get("surface") else "mentor_rejected",
            idea=idea["idea"],
            dimension=idea.get("dimension"),
            falsifiable_test=idea["falsifiable_test"],
            would_be_false_if=idea["would_be_false_if"],
            test_horizon=horizon_date,
            outcome=None,
            surface=bool(m.get("surface")),
            mentor=m.get("mentor"),
            mentor_proof=m.get("proof"),
            penumbra=m.get("penumbra"),
            articulated_by=idea.get("articulated_by", "llm"),
            language="en",
        ))
        if len([r for r in records if r.get("status") == "accepted"]) >= MAX_IDEAS_PER_TICK:
            break

    if dry_run:
        for r in records:
            print(json.dumps(r, ensure_ascii=False))
        return records

    MEMORY.mkdir(parents=True, exist_ok=True)
    with IDEA_STREAM.open("a", encoding="utf-8") as fh:
        for r in records:
            fh.write(json.dumps(r, ensure_ascii=False) + "\n")
    return records


# ---------------------------------------------------------------------------
# STATUS / SCORING
# ---------------------------------------------------------------------------

def status():
    rows = _read_jsonl(IDEA_STREAM)
    if not rows:
        return {"stream": str(IDEA_STREAM), "exists": IDEA_STREAM.exists(), "total": 0,
                "note": "no ideas yet - the creative phase has produced nothing"}
    accepted = [r for r in rows if r.get("status") == "accepted"]
    resolved = [r for r in accepted if r.get("outcome") is not None]
    correct = [r for r in resolved if r.get("outcome") is True]
    reasons = {}
    for r in rows:
        if r.get("status") == "rejected":
            reasons[r.get("reject_reason")] = reasons.get(r.get("reject_reason"), 0) + 1
    return {
        "stream": str(IDEA_STREAM),
        "total": len(rows),
        "accepted": len(accepted),
        "mentor_rejected": len([r for r in rows if r.get("status") == "mentor_rejected"]),
        "guard_rejected": len([r for r in rows if r.get("status") == "rejected"]),
        "reject_reasons": reasons,
        "resolved": len(resolved),
        "correct": len(correct),
        "predictive_accuracy": (round(len(correct) / len(resolved), 3) if resolved else None),
        "NOT_A_METRIC": "accept-rate. Never report it as quality. An idea generator scored on approval learns to please.",
    }


def due():
    now = _now()
    out = []
    for r in _read_jsonl(IDEA_STREAM):
        if r.get("status") != "accepted" or r.get("outcome") is not None:
            continue
        h = r.get("test_horizon")
        if not h:
            continue
        dt = _try(lambda: datetime.strptime(h, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc))
        if dt and dt <= now:
            out.append(r)
    return out


def selftest():
    """Report which parts of this module are actually live in THIS repo.

    Exists because a module that degrades silently lets a claim like 'the
    mentor pass checks each idea' stay true on paper and false on disk.
    """
    oracle = _load_metta_oracle()
    llm = _load_llm()
    report = {
        "repo_root": str(REPO),
        "idea_stream": str(IDEA_STREAM),
        "idea_stream_exists": IDEA_STREAM.exists(),
        "seed_gen_1_rule_violations": "LIVE" if oracle else "INERT - core.metta_oracle not importable",
        "seed_gen_2_trends": "LIVE (pure python, no dependency)",
        "mentor_pass": "LIVE" if oracle else "INERT - every idea surfaces unchecked",
        "penumbra_model_anomaly_door": "REACHABLE" if oracle else "UNREACHABLE",
        "articulation": "LLM" if llm else "deterministic fallback - core.groq_backend.call_groq not importable",
        "guards": ["grounded_on refs must exist on disk", "falsifiable_test required",
                   "integer horizon_days required", "would_be_false_if required",
                   "non-ASCII output rejected as non_english_output"],
        "writes": [str(IDEA_STREAM)],
        "actuates": "nothing",
    }
    degraded = [k for k, v in report.items() if isinstance(v, str) and ("INERT" in v or "UNREACHABLE" in v)]
    report["DEGRADED"] = degraded or "none"
    return report


def main():
    ap = argparse.ArgumentParser(description="CORTEX background creative tick")
    ap.add_argument("--selftest", action="store_true", help="report which integrations are actually live")
    ap.add_argument("--dry-run", action="store_true", help="print, write nothing")
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--due", action="store_true", help="ideas whose horizon has passed and await a verdict")
    ap.add_argument("--levels", default=None, help="path to a JSON file of current axis levels")
    ap.add_argument("--series", default=None, help="path to a JSON file of {axis: [values]}")
    args = ap.parse_args()

    if args.selftest:
        print(json.dumps(selftest(), indent=2))
        return 0
    if args.status:
        st = status()
        st["integrations"] = {k: v for k, v in selftest().items()
                              if k.startswith("seed_gen") or k in ("mentor_pass", "articulation", "DEGRADED")}
        print(json.dumps(st, indent=2))
        return 0
    if args.due:
        for r in due():
            print(json.dumps({"seed_key": r["seed_key"], "idea": r["idea"],
                              "test": r["falsifiable_test"], "horizon": r["test_horizon"]}, indent=2))
        return 0

    levels = json.loads(Path(args.levels).read_text(encoding="utf-8")) if args.levels else {}
    series = json.loads(Path(args.series).read_text(encoding="utf-8")) if args.series else {}
    grounded = [p for p in ("memory/existence_ledger.jsonl", "config/target_config.json") if (REPO / p).exists()]
    recs = run_tick(levels, series, grounded, dry_run=args.dry_run)
    print("creative_tick: %d records (%d accepted)" % (
        len(recs), len([r for r in recs if r.get("status") == "accepted"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
